// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdOBFxPS1TacnK5OZTU6VxOQ20Bq8Cyrg',
    appId: '1:79998394043:web:95361b63452944add6139e',
    messagingSenderId: '79998394043',
    projectId: 'thermal-effort-366015',
    authDomain: 'thermal-effort-366015.firebaseapp.com',
    storageBucket: 'thermal-effort-366015.appspot.com',
    measurementId: 'G-70WYNB4CN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpxDuMIZrx55W6YuU6TY0v7T3Ar-Mg-Eo',
    appId: '1:79998394043:android:c36642e037a239b5d6139e',
    messagingSenderId: '79998394043',
    projectId: 'thermal-effort-366015',
    storageBucket: 'thermal-effort-366015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXm4T-m7LSN9MzmMKIx7DwFWYi_IFVpVA',
    appId: '1:79998394043:ios:3910aefbd1ad3f26d6139e',
    messagingSenderId: '79998394043',
    projectId: 'thermal-effort-366015',
    storageBucket: 'thermal-effort-366015.appspot.com',
    androidClientId: '79998394043-2llu6cka2h7lijqk1kds6m2056ub99vu.apps.googleusercontent.com',
    iosClientId: '79998394043-j7dfaotb938e8d57fmfbkthcdq3jup1i.apps.googleusercontent.com',
    iosBundleId: 'com.boha.kasieTransieRouteBuilder2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXm4T-m7LSN9MzmMKIx7DwFWYi_IFVpVA',
    appId: '1:79998394043:ios:70f12ff726f6c9ced6139e',
    messagingSenderId: '79998394043',
    projectId: 'thermal-effort-366015',
    storageBucket: 'thermal-effort-366015.appspot.com',
    androidClientId: '79998394043-2llu6cka2h7lijqk1kds6m2056ub99vu.apps.googleusercontent.com',
    iosClientId: '79998394043-hm6c7309a64tmeguve6ab7ci6jfmst68.apps.googleusercontent.com',
    iosBundleId: 'com.boha.kasieTransieRouteBuilder2.RunnerTests',
  );
}
